import { Authenticated, Refine } from "@refinedev/core";
import { DevtoolsPanel, DevtoolsProvider } from "@refinedev/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from "@refinedev/react-router";
import { dataProvider, liveProvider } from "@refinedev/supabase";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { useEffect, useState } from "react";
import "./App.css";
import authProvider from "./authProvider";
import { supabaseClient } from "./utility";
import { LoginPage } from "./pages/Login";
import { AdminPortal } from "./portals/admin/AdminPortal";
import { PilotPortal } from "./portals/pilot/PilotPortal";
import { EditorPortal } from "./portals/editor/EditorPortal";
import { ClientPortal } from "./portals/client/ClientPortal";
import { PortalRoute } from "./portals/shared/PortalRoute";
import { portalBasePath, resolveUserRole } from "./portals/shared/role";

const LandingRedirect = () => {
  const [target, setTarget] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    const route = async () => {
      const role = await resolveUserRole();
      if (!mounted) return;
      setTarget(portalBasePath(role));
    };
    route();
    return () => {
      mounted = false;
    };
  }, []);

  if (!target) {
    return (
      <div className="page-shell">
        <p>Loading portal...</p>
      </div>
    );
  }

  return <Navigate to={target} replace />;
};

const ProtectedRoutes = () => (
  <Routes>
    <Route path="/" element={<LandingRedirect />} />
    <Route
      path="/admin/*"
      element={
        <PortalRoute allowed={["admin", "owner"]}>
          <AdminPortal />
        </PortalRoute>
      }
    />
    <Route
      path="/pilot/*"
      element={
        <PortalRoute allowed={["pilot"]}>
          <PilotPortal />
        </PortalRoute>
      }
    />
    <Route
      path="/editor/*"
      element={
        <PortalRoute allowed={["editor"]}>
          <EditorPortal />
        </PortalRoute>
      }
    />
    <Route
      path="/client/*"
      element={
        <PortalRoute allowed={["client"]}>
          <ClientPortal />
        </PortalRoute>
      }
    />
    <Route path="*" element={<Navigate to="/" replace />} />
  </Routes>
);

function App() {
  return (
    <BrowserRouter>
      <RefineKbarProvider>
        <DevtoolsProvider>
          <Refine
            dataProvider={dataProvider(supabaseClient)}
            liveProvider={liveProvider(supabaseClient)}
            authProvider={authProvider}
            routerProvider={routerProvider}
            options={{
              syncWithLocation: true,
              warnWhenUnsavedChanges: true,
              projectId: "7bfsGC-5DoEI4-5uF75J",
              title: { text: "Buzz Portal" },
            }}
            resources={[
              {
                name: "profiles",
                list: "/admin/profiles",
              },
              {
                name: "bookings",
                list: "/admin/bookings",
                show: "/admin/bookings/:id",
              },
              {
                name: "booking_media_files",
                list: "/admin/bookings/:id",
              },
              {
                name: "booking_editors",
                list: "/admin/bookings/:id",
              },
            ]}
          >
            <Routes>
              <Route path="/login" element={<LoginPage />} />
              <Route
                path="*"
                element={
                  <Authenticated
                    key="authenticated"
                    fallback={<Navigate to="/login" replace />}
                  >
                    <ProtectedRoutes />
                  </Authenticated>
                }
              />
            </Routes>
            <RefineKbar />
            <UnsavedChangesNotifier />
            <DocumentTitleHandler
              handler={({ autoGeneratedTitle }) =>
                autoGeneratedTitle.replace(/Refine/g, "Buzz Portal")
              }
            />
          </Refine>
          <DevtoolsPanel />
        </DevtoolsProvider>
      </RefineKbarProvider>
    </BrowserRouter>
  );
}

export default App;
